// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiORzBh1Hzf5zRHKc5ESfdh_Mw6sOIg_s',
    appId: '1:495340041439:web:95a2db456e4c530f15656a',
    messagingSenderId: '495340041439',
    projectId: 'boifiok',
    authDomain: 'boifiok.firebaseapp.com',
    storageBucket: 'boifiok.firebasestorage.app',
    measurementId: 'G-K7N9EYN829',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh3upjZd274M0b4exxUuhkjoETXOG3vFM',
    appId: '1:495340041439:android:d0721ad2c33f5dc815656a',
    messagingSenderId: '495340041439',
    projectId: 'boifiok',
    storageBucket: 'boifiok.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfe-CN_LVCAO_sNVJfopPVtHWgZ9OQKnI',
    appId: '1:495340041439:ios:338bed7ad0b8282d15656a',
    messagingSenderId: '495340041439',
    projectId: 'boifiok',
    storageBucket: 'boifiok.firebasestorage.app',
    iosClientId: '495340041439-b99a5l481i5pkapu2qon44k8orv9601s.apps.googleusercontent.com',
    iosBundleId: 'com.example.boifiok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfe-CN_LVCAO_sNVJfopPVtHWgZ9OQKnI',
    appId: '1:495340041439:ios:338bed7ad0b8282d15656a',
    messagingSenderId: '495340041439',
    projectId: 'boifiok',
    storageBucket: 'boifiok.firebasestorage.app',
    iosClientId: '495340041439-b99a5l481i5pkapu2qon44k8orv9601s.apps.googleusercontent.com',
    iosBundleId: 'com.example.boifiok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiORzBh1Hzf5zRHKc5ESfdh_Mw6sOIg_s',
    appId: '1:495340041439:web:e1a49e9b6f7d494715656a',
    messagingSenderId: '495340041439',
    projectId: 'boifiok',
    authDomain: 'boifiok.firebaseapp.com',
    storageBucket: 'boifiok.firebasestorage.app',
    measurementId: 'G-5MYBKLCTNF',
  );
}
